mkdir data
chmod 777 data

cat << EOF > ./startup.sql
alter session set "_ORACLE_SCRIPT"=true;
DROP USER ORACLEUSR CASCADE; 

alter session set "_ORACLE_SCRIPT"=true;  
CREATE USER ORACLEUSR IDENTIFIED BY ORACLEUSR;

GRANT CONNECT TO ORACLEUSR;

GRANT CONNECT, RESOURCE, DBA TO ORACLEUSR;

GRANT UNLIMITED TABLESPACE TO ORACLEUSR;

CREATE TABLE ORACLEUSR.RUBRICA (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nome VARCHAR2(50),
  cognome VARCHAR2(50),
  CONSTRAINT RUBRICA_PK PRIMARY KEY (id)
);
INSERT INTO ORACLEUSR.RUBRICA (nome, cognome) VALUES ('Mario', 'Rossi');
INSERT INTO ORACLEUSR.RUBRICA (nome, cognome) VALUES ('Luca', 'Bianchi');
INSERT INTO ORACLEUSR.RUBRICA (nome, cognome) VALUES ('Anna', 'Verdi');
EOF




docker run -d -p 1521:1521 --name myoracle -e ORACLE_PASSWORD=oracle -v $PWD/tmp:/work -v $PWD/data:/opt/oracle/oradata -v $PWD/startup.sql:/docker-entrypoint-initdb.d/startup.sql gvenzl/oracle-xe:21

